name: Create Helm chart

on:
  # push:
  #   branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CHART_ROOT_FOLDER: charts
  PUBLIC: 20.103.115.121.nip.io

jobs:
  create-chart:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set ENV variables
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          CHART_APP_FOLDER="${CHART_ROOT_FOLDER}/${REPO_NAME}"
          echo "REPO_NAME=${REPO_NAME}" >> "$GITHUB_ENV"
          echo "CHART_APP_FOLDER=${CHART_APP_FOLDER}" >> "$GITHUB_ENV"

      - uses: azure/setup-helm@v3
        with:
          version: 'v3.11.3' # default is latest (stable)
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
      
      - name: Create chart 
        run: |
          mkdir charts && helm create ${CHART_APP_FOLDER}
          sed -i '/0.1.0/ s//0.0.1/g' ${CHART_APP_FOLDER}/Chart.yaml
          sed -i '/1.16.0/ s//0.0.1/g' ${CHART_APP_FOLDER}/Chart.yaml

      - name: Configure values.yaml
        uses: mikefarah/yq@master
        with:
          cmd: |
            RP=$GITHUB_REPOSITORY yq -i '.image.repository = env(RP)' ${{ env.CHART_APP_FOLDER }}/values.yaml
            yq -i '.ingress.enabled = true' ${{ env.CHART_APP_FOLDER }}/values.yaml
            yq -i '.ingress.className = "nginx"' ${{ env.CHART_APP_FOLDER }}/values.yaml

      - name: Set TLS config
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '.ingress.annotations."cert-manager.io/cluster-issuer"="letsencrypt"' ${{ env.CHART_APP_FOLDER }}/values.yaml
            PUBLIC=$PUBLIC RP=$REPO_NAME yq -i '.ingress.tls = {"hosts": [env(RP)+"."+env(PUBLIC)], "secretName": env(RP)+"-tls"}' ${{ env.CHART_APP_FOLDER }}/values.yaml
            PUBLIC=$PUBLIC RP=$REPO_NAME yq -i '.ingress.hosts[0] = {"host": env(RP)+"."+env(PUBLIC)}' ${{ env.CHART_APP_FOLDER }}/values.yaml
            yq -i '.ingress.hosts[0].paths[0].path = "/" | .ingress.hosts[0].paths[0].pathType= "ImplementationSpecific"' ${{ env.CHART_APP_FOLDER }}/values.yaml

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Github actions - Chart creation"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          

