name: Push Helm Chart to GHR

on:
  # push:
  #   branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ARGO_SERVER: ${{ env.ARGO_SERVER }} # Set these variables on Settings -> Secrets & variables -> actions
  CHART_SERVER: ${{ env.CHART_SERVER }}
  CHART_ROOT_FOLDER: charts

jobs:
  helm-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set ENV variables
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          CHART_APP_FOLDER="${CHART_ROOT_FOLDER}/${REPO_NAME}"
          echo "REPO_NAME=${REPO_NAME}" >> "$GITHUB_ENV"
          echo "CHART_APP_FOLDER=${CHART_APP_FOLDER}" >> "$GITHUB_ENV"
      
      - name: Set Application version 
        run: |
          OUTPUT=$(grep ^appVersion $CHART_APP_FOLDER/Chart.yaml | awk '{ print $2 }' | tr -d '"')
          echo "APP_VERSION=$OUTPUT" >> "$GITHUB_ENV"

      - name : Set Helm chart version
        run: |
          OUTPUT=$(grep ^version $CHART_APP_FOLDER/Chart.yaml | awk '{ print $2 }')
          echo "CHART_VERSION=$OUTPUT" >> "$GITHUB_ENV"                    

      - name: Push Helm chart to Chartmuseum
        uses: bsord/helm-push@v4.1.0
        with:
          registry-url: ${{ env.CHART_SERVER }}
          username: ${{ secrets.CHART_USER }}
          password: ${{ secrets.CHART_PASSWD }}
          force: true
          chart-folder: ${{ env.CHART_APP_FOLDER }}

      - name: Setup ArgoCD CLI 
        uses: imajeetyadav/argocd-cli@v1
        with:
          version: v2.7.1 # optional 
      
      - name: Check Argo CD CLI version
        run: |
          argocd login $ARGO_SERVER --username ${{ secrets.ARGO_USER }} --password ${{ secrets.ARGO_PASSWD }}
          echo "argocd app set argocd/$REPO_NAME --project default --revision $CHART_VERSION"

      # - name: Push Helm chart to OCI compatible registry (Github)
      #   uses: bsord/helm-push@v4.1.0
      #   with:
      #     useOCIRegistry: true
      #     registry-url:  oci://ghcr.io/${{ github.repository }}
      #     username: ${{ github.repository_owner }}
      #     access-token: ${{ secrets.GITHUB_TOKEN }}
      #     force: true
      #     chart-folder: app01
